[project]
name = "Decomplicator"
version = "1.0.5"
description = "Sets up development environments for Nintendo 64 decompilation projects on Windows."
requires-python = ">=3.14"
dependencies = [
    "pyside6-essentials==6.11.1",
    "requests==2.34.2",
    "pyinstaller==6.21.0",
    "pillow==12.3.0",  # used by PyInstaller
]

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
namespace = true